#pragma config(Sensor, dgtl7,  leftdriveencoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  rightdriveencoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           leftdrive1,    tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           leftdrive2,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightdrive2,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rightdrive1,   tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turndistance (int degrees, int power, int type)
{
	SensorValue(leftdriveencoder) = 0;
	SensorValue(rightdriveencoder) = 0;
	repeatUntil(abs(SensorValue(leftdriveencoder)) >= degrees && abs(SensorValue(rightdriveencoder)) >= degrees)
	{
		motor[leftdrive1] = -power;
		motor[leftdrive2]  = -power;
		motor[rightdrive1] = 0.91*power;
		motor[rightdrive2]  = 0.91*power;
	}
	SensorValue(leftdriveencoder) = 0;
	SensorValue(rightdriveencoder) = 0;

	if (type == 1)
	{
		if (power > 0)
		{
			motor[leftdrive1] = 10;
			motor[leftdrive2] = 10;
			motor[rightdrive2] = -10;
			motor[rightdrive1] = -10;
		}
		else
		{
			motor[leftdrive1] = -10;
			motor[leftdrive2] = -10;
			motor[rightdrive2] = 10;
			motor[rightdrive1] = 10;
		}
	}
	if (type == 0)
	{
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		motor[rightdrive2] = 0;
		motor[rightdrive1] = 0;
	}
}

task main()
{
  SensorValue[leftdriveencoder] = 0;
  SensorValue[rightdriveencoder] = 0;
  turndistance(40000000,-40,0);
  wait1Msec(500);
}
